Added LevelSelection-v1,  new anims to AnimationUtility
adhxll/Pollo2 pull request #5
Opened 2021-11-11 06:01 UTC by TheSpartaGod

1st version of level selection, semua level ketika diklik baru akan pergi ke level yang sama. Added anims for popup and disappear. Button setting belom bisa karena scenenya belom ada.

2021-11-11 12:57 UTC, adhxll requested changes
Scene files:
-
1. LevelSelection => (0,0) coordinate for every gameObject that is empty or only holds scripts 
=> I don’t think it’s necessary to have 2 canvas to group different elements. Make it into 1 UI canvas, but group anything you want using empty game objects 
=> the overlay and modal would be better if it were grouped together, since it operates together 
=> Setting button is still not standardized, refer to design documentation in figma 
=> Close button at the modals are supposed to be purple, and use the recommended size
 => Rename ‘Text’ object in UICanvas into ‘StageName’ and use the hifi design => Text object in UICanvas sizing is still in floats, change the scale into 1 1 1 
 => Even though we’re just trying to reach the acceptance criteria, try to match the existing design MVP into our design (like the stage name color, level header design, etc) (but consult this to the design team)
2. LevelItem prefab => change ‘Text’ into level name => scales and stuff, use integer not floats

Controller files:
-
1. LevelSelectionController.cs => organize the code inside Awake() into functions so it’s clean and organized and makes it clear what is it that’s happening inside the Awake() function 
=> clean up the indentation and newlines between functions
2. ModalController.cs => levelselectioncontroller is still the one controlling the modal, so I think the modal controller hasn’t been utilized effectively. Either delete this class or migrate the functions from LevelSelectionController into this class.


Utilities files:
-
1. (low priority, because it’s for another backlog) LevelItem.cs => this file contains 2 classes, separate them 
=> Class LevelItemContainer needs to be discussed since it still uses the old ERD
 => Class LevelItem might need something called ScriptableObject since you want to programmatically set the prefab. And organize the code in Start() function so it’s clear what’s happening inside the function
2. AnimationUtilities.cs => add general documentation to each function you add because it’s a very general class that gets used by other engineers
3. StarCount.cs => This class might only be relevant in levelselect scene, so consider moving it into the levelselect folder. But if it can be used by other scenes, do write the brief documentation. 
 => Also, remove unnecessary comments

Helper files:
-

Framework / Library files (All the libraries used within this project are matched and based on the requirements):
-

Asset files:
-

Architecture:
-

Code convention & style:
-

Performance / memory management:
-
1. The level prefab can be more memory efficient if you use ScriptableObject

2021-11-12 07:20 UTC, TheSpartaGod commented
Scene files: 
1. did everything except change the canvas, because it's necessary, and some text elements, because someone is creating a prefab for it.
2. Done
Controller files: 
1. Done
2. Done
Utilities files: 
1. Separated, made a new script called "LevelItemContainer"
2. Done
3. Added new docs because it can be used on multiple scenes
Performance / memory management: 
1. Nanti kalo udah ada level baru dari sam gua ubah, soalnya gw rasa mending port ke ScriptableObject kalo udah bener semua functionalitynya, TANGGUNG SISS

Please re-review epicly

2021-11-12 13:46 UTC, adhxll requested changes
Scene files:
-
1. LevelSelection => LevelCanvas components still have non-integer values :D 
=> The SettingButton should be size small, it’s currently medium size. The small size is 33x35 btw! 
 => So Modal and Overlay can’t be grouped into the same object?
2. LevelItem => some values are still in floats 
=> I think you should consider using Image components instead of Sprite Renderer for the Tag and Stars because you can just use the measurements from Figma directly.

Controller files:
-

Utilities files:
-
1. AnimationUtilities.cs => after really looking at what each button does, I think each function is quite redundant because all it does is scale an object to a certain degree. I think we can optimize this using enum and case and also make a general scale animation with a float parameter between 0-1. This is quite a low priority, so let’s leave it for now.

Helper files:
-

Framework / Library files (All the libraries used within this project are matched and based on the requirements):
-

Asset files:
-

Architecture:
-

Code convention & style:
-

Performance / memory management:
-

2021-11-12 16:36 UTC, zeinrezky approved these changes

2021-11-15 14:53 UTC, adhxll approved these changes

2021-11-15 15:01 UTC, merged